version: '2'
services:
    operam-nginx:
        container_name: operam-nginx
        build: docker/images-prod/nginx
        image: operam-nginx
        volumes:
            - ./:/app
            - /etc/localtime:/etc/localtime:ro
        environment:
            - VIRTUAL_HOST=operam.net
        networks:
            operam-network:
                aliases:
                    - operam-nginx
        expose:
            - 80
        ports:
            - "80:80"
        restart: always

    operam-node:
        container_name: operam-node
        build: docker/images-prod/node
        image: operam-node
        volumes:
            - ./:/app
            - /etc/localtime:/etc/localtime:ro
        working_dir: /app
        networks:
            operam-network:
                aliases:
                    - operam-node
        restart: always
        expose:
            - 3000

networks:
    operam-network:
